version: "2.1"
services:
  wireshark:
    image: lscr.io/linuxserver/wireshark:arm32v7-3.4.13
    container_name: wireshark
    cap_add:
      - NET_ADMIN
    security_opt:
      - seccomp:unconfined #optional
    network_mode: host
    environment:
      #- PUID=1000
      #- PGID=1000
      - TZ=Europe/London
      - CUSTOM_PORT=8000
    volumes:
      - /mnt/usbdrive/docker/volumes/wireshark:/config
    ports:
      - 3030:3000 #optional
    restart: unless-stopped

