version: '3'
services:
  nginx:
    container_name: nginx
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"    
    volumes:
      - ${DATADIR}/volumes/nginx/html:/usr/share/nginx/html
      - ${DATADIR}/conf/nginx/nginx.conf:/etc/nginx/nginx.conf
      - letsencrypt-certs:/etc/letsencrypt
      - letsencrypt-www:/var/www/certbot
    restart: always
    network_mode: host
  certbot:
    container_name: certbot
    image: certbot/certbot
    volumes:
      - letsencrypt-certs:/etc/letsencrypt
      - letsencrypt-www:/var/www/certbot
      - ${DATADIR}/logs/letsencrypt:/var/log/letsencrypt
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    network_mode: host

volumes:
  letsencrypt-www:
  letsencrypt-certs: